# -*- coding: utf-8 -*-
"""interes_compuesto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCKMlL4GS8EyohRpUVi6elTDIcz9Cqkc
"""

import matplotlib.pyplot as plt

# Entrada de datos
PV = float(input("Contribución Inicial:"))
R = float(input("Tasa de Interés (%):"))
N = int(input("Número de Periodos:"))
aporte_mensual = float(input("Contribución/Extracción Mensual (positivo=aporte, negativo=retiro):"))

# Calcular valores con aportes mensuales
periodos = list(range(N + 1))
capital = [PV]  # Empezamos con el capital inicial
interes = [0]   # Interés inicial en 0
aportes_acumulados = [0]  # Total aportado hasta cada periodo

for t in range(1, N + 1):
    # Interés del periodo anterior
    interes_ganado = capital[-1] * R

    # Nuevo capital = capital anterior + interés + aporte mensual
    nuevo_capital = capital[-1] + interes_ganado + aporte_mensual

    capital.append(nuevo_capital)
    interes.append(nuevo_capital - PV - (aporte_mensual * t))  # Interés = capital - (inicial + aportes)
    aportes_acumulados.append(aporte_mensual * t)

# Crear gráficos
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))

# Gráfico 1: Evolución del capital total
ax1.plot(periodos, capital, 'b-', linewidth=2, label='Capital Total')
ax1.axhline(y=PV, color='r', linestyle='--', linewidth=1.5, label='Capital Inicial')
if aporte_mensual != 0:
    ax1.plot(periodos, [PV + aporte_mensual * t for t in periodos], 'g--',
             linewidth=1.5, label='Capital + Aportes (sin interés)')
ax1.set_xlabel('Periodos')
ax1.set_ylabel('Monto ($)')
ax1.set_title('Evolución del Capital')
ax1.grid(True, alpha=0.3)
ax1.legend()

# Gráfico 2: Interés generado
ax2.plot(periodos, interes, 'orange', linewidth=2, label='Interés Acumulado')
ax2.fill_between(periodos, 0, interes, alpha=0.3, color='orange')
ax2.set_xlabel('Periodos')
ax2.set_ylabel('Interés ($)')
ax2.set_title('Interés Generado')
ax2.grid(True, alpha=0.3)
ax2.legend()

# Gráfico 3: Desglose del capital (si hay aportes)
if aporte_mensual != 0:
    capital_inicial = [PV] * (N + 1)
    aportes = [aporte_mensual * t for t in periodos]
    intereses = [capital[t] - PV - aporte_mensual * t for t in periodos]

    ax3.stackplot(periodos, capital_inicial, aportes, intereses,
                  labels=['Capital Inicial', 'Aportes', 'Interés'],
                  colors=['#ff9999', '#66b3ff', '#99ff99'], alpha=0.7)
    ax3.set_xlabel('Periodos')
    ax3.set_ylabel('Monto ($)')
    ax3.set_title('Desglose del Capital')
    ax3.legend(loc='upper left')
    ax3.grid(True, alpha=0.3)
else:
    ax3.text(0.5, 0.5, 'Sin aportes mensuales',
             horizontalalignment='center', verticalalignment='center',
             transform=ax3.transAxes, fontsize=14)
    ax3.set_title('Desglose del Capital')

# Gráfico 4: Aportes acumulados
if aporte_mensual != 0:
    ax4.bar(periodos, [aporte_mensual] * (N + 1), alpha=0.5, color='blue', label='Aporte mensual')
    ax4.plot(periodos, aportes_acumulados, 'r-', linewidth=2, label='Aportes acumulados')
    ax4.set_xlabel('Periodos')
    ax4.set_ylabel('Monto ($)')
    ax4.set_title('Aportes Mensuales')
    ax4.grid(True, alpha=0.3)
    ax4.legend()
else:
    ax4.text(0.5, 0.5, 'Sin aportes mensuales',
             horizontalalignment='center', verticalalignment='center',
             transform=ax4.transAxes, fontsize=14)
    ax4.set_title('Aportes Mensuales')

plt.tight_layout()
plt.show()

# Mostrar resumen
print("\n" + "="*50)
print("RESUMEN DE LA INVERSIÓN")
print("="*50)
print(f"Capital Inicial: ${PV:,.2f}")
print(f"Tasa de Interés: {R*100:.1f}%")
print(f"Periodos: {N}")
if aporte_mensual > 0:
    print(f"Aporte Mensual: ${aporte_mensual:,.2f}")
    print(f"Total Aportado: ${aporte_mensual * N:,.2f}")
elif aporte_mensual < 0:
    print(f"Retiro Mensual: ${abs(aporte_mensual):,.2f}")
    print(f"Total Retirado: ${abs(aporte_mensual * N):,.2f}")
else:
    print("Sin aportes mensuales")
print("-"*50)
print(f"Capital Final: ${capital[-1]:,.2f}")
print(f"Interés Total Generado: ${interes[-1]:,.2f}")
print(f"Rendimiento Total: {((capital[-1] / (PV + aporte_mensual * N)) - 1) * 100:.2f}%")